_wandb:
    value:
        cli_version: 0.29.0
        e:
            v2k66kvzrn7g67w6co87w56j0y485wwa:
                codePath: /home/dimitria/PhD_codes/learning_on_the_fly/examples/state_hovering/train_residual_dyn_full.ipynb
                codePathLocal: train_residual_dyn_full.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2013991550976"
                        used: "335268032512"
                email: dimitriasilveria.ds@gmail.com
                executable: /home/dimitria/venvs/diff-sim-env/bin/python
                git:
                    commit: 10112648100e49f8366274770b210ddb7456f063
                    remote: git@github.com:dimitriasilveria/variational_neural_dynamics.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-46e18f80-8f60-4640-0d33-9cc1b21361ca
                host: quarrg-Alienware-Aurora-R12-dimitria
                memory:
                    total: "67082342400"
                os: Linux-7.0.0-30-generic-x86_64-with-glibc2.39
                program: /home/dimitria/PhD_codes/learning_on_the_fly/examples/state_hovering/train_residual_dyn_full.ipynb
                python: CPython 3.12.3
                root: /home/dimitria/PhD_codes/learning_on_the_fly/examples/state_hovering
                startedAt: "2026-08-27T14:55:04.302110Z"
                writerId: v2k66kvzrn7g67w6co87w56j0y485wwa
        m:
            - "1": continual/round
              "6":
                - 3
              "7": []
            - "1": dynamics/update
              "6":
                - 3
              "7": []
            - "2": parameters/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": timing/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": dynamics/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": policy/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": dynamics_round/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": replay/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": collection/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": encoder/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 2
                - 7
                - 16
            "4": 3.12.3
            "5": 0.29.0
            "8":
                - 1
            "12": 0.29.0
            "13": linux-x86_64
context_length:
    value: 20
control_delay:
    value: 0.04
dynamics_horizon:
    value: 110
dynamics_learning_rate:
    value: 0.0003
dynamics_updates_per_round:
    value: 1000
lambda_mmd_max:
    value: 9e-05
lambda_rec:
    value: 1e-07
latent_dim:
    value: 12
mmd_kernel_sigma:
    value: 2
mmd_ramp_updates:
    value: 2500
mmd_warmup_updates:
    value: 800
num_continual_rounds:
    value: 10000
policy_discount:
    value: 1
policy_learning_rate:
    value: 0.001
policy_num_envs:
    value: 512
policy_rollout_horizon:
    value: 250
policy_updates_per_round:
    value: 1
replay_batch_size:
    value: 128
residual_huber_delta:
    value: 1
reward_huber_delta:
    value: 1
rollouts_per_collection_round:
    value: 256
seed:
    value: 0
sim_dt:
    value: 0.02
